### PR TITLE
ISPN-9373 Update testng to the latest version

### PR DESCRIPTION
**Pull request by diegolovison**
* When updating to 6.14.3 the following classes started reporting compilation errors:
CustomMarshallerEventIT.java
NamedTestMethod.java
XMLTranscoderTest.java
SpringRemoteCacheManagerFactoryBeanContextTest.java

* `<disableXmlReport>false</disableXmlReport>` and `<usedefaultlisteners>false</usedefaultlisteners>` We will let `PolarionJUnitXMLReporter` generate the reports to us. There are projects that contains a mix of Junit and TestNG tests and setting this equals false was generating a third report. The third report is the content of the testNG and the Junit report. Let's say (this is an example) that the junit report contains 10 tests and testNG 20 tests. The third report will be generated with 30 tests. The "Test Result" in Jenkins will show a wrong number of tests. In this case, 60 tests will be reported.

* I don't see any major issue with `Force use of JUnit, since TestNG+Arquillian break in wonderful ways`. I removed those workarounds.

* Without the new dependency `<artifactId>testng</artifactId>` and keeping the plugin `<artifactId>surefire-junit47</artifactId>` was generating an error before the test phase have been started. In this case, the project will be SUCCESS with 0 tests, 0 failures, 0 errors, 0 skipped.

* Jenkinsfile - Using the new version of testNG. The tests now are under a subfolder and start with "TEST-"

* PolarionJUnitXMLReporter.java - We delegate the whole process to `JUnitReportReporter` and kept the custom code that we need that is related to the tests case name. 
```java
Utils.writeUtf8File(suite.getOutputDirectory().replaceAll(".Surefire suite", ""),           generateFileName(suite) + ".xml", document.toXML());
``` 
The code above is not needed because the new version don't generate folders with space.

### CODE REVIEW

**Comment by diegolovison** [comment]
@alanfx:
From the commit 3082f7822a8083724b8ab096cdcdbff2606f8aff we got the following results from the log. This build run in DEV-CI.
```
diego@diego-note:~/Downloads/grep$ ./run.sh consoleText_dev_1.txt 
==========FAILURE==========
[ERROR] ScatteredSplitAndMergeTest(org.infinispan.partitionhandling.ScatteredSplitAndMergeTest)  Time elapsed: 0.036 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0.001 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] query.blackbox.ClusteredCacheWithAffinityIndexManagerTxTest(org.infinispan.query.blackbox.ClusteredCacheWithAffinityIndexManagerTxTest)  Time elapsed: 0.155 s  <<< FAILURE!
[ERROR] query.blackbox.ClusteredCacheWithAffinityIndexManagerTest(org.infinispan.query.blackbox.ClusteredCacheWithAffinityIndexManagerTest)  Time elapsed: 2.503 s  <<< FAILURE!
[ERROR] query.blackbox.ClusteredCacheWithAffinityIndexManagerTxTest(org.infinispan.query.blackbox.ClusteredCacheWithAffinityIndexManagerTxTest)  Time elapsed: 5.582 s  <<< FAILURE!
[ERROR] query.blackbox.ClusteredCacheWithAffinityIndexManagerTest(org.infinispan.query.blackbox.ClusteredCacheWithAffinityIndexManagerTest)  Time elapsed: 0.99 s  <<< FAILURE!
[ERROR] scripting.ScriptingTest(org.infinispan.scripting.ScriptingTest)  Time elapsed: 0.19 s  <<< FAILURE!
[ERROR] client.hotrod.event.ClientClusterFailoverEventsTest(org.infinispan.client.hotrod.event.ClientClusterFailoverEventsTest)  Time elapsed: 0.55 s  <<< FAILURE!
==========FAILURE==========

===========ERROR===========
===========ERROR===========

Tests run: 24542
Failures: 13
Errors: 0
Skipped: 51

```

From the commit 3082f7822a8083724b8ab096cdcdbff2606f8aff we got the following results from the log. This build run in QE-CI.
```
==========FAILURE==========
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0.013 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0.026 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0.001 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0 s  <<< FAILURE!
[ERROR] functional.FunctionalListenersTest(org.infinispan.functional.FunctionalListenersTest)  Time elapsed: 0.001 s  <<< FAILURE!
[ERROR] query.blackbox.ClusteredCacheWithAffinityIndexManagerTest(org.infinispan.query.blackbox.ClusteredCacheWithAffinityIndexManagerTest)  Time elapsed: 0.192 s  <<< FAILURE!
[ERROR] scripting.ScriptingTest(org.infinispan.scripting.ScriptingTest)  Time elapsed: 0.205 s  <<< FAILURE!
==========FAILURE==========

===========ERROR===========
===========ERROR===========

Tests run: 26771
Failures: 8
Errors: 0
Skipped: 135

```

I was expecting the same "Tests run", "Failures", "Errors" and "Skipped" when running in "Linux". I am closing this PR because more work is needed.
