### ISSUE TITLE
SimpleApplicationTests fails in spring-boot-3 embedded IT — Micrometer version mismatch

### ISSUE THREAD

**Issue by wburns** [infinispan/infinispan#17991]
### Describe the bug
The `SimpleApplicationTests.contextLoads` test in `infinispan-spring-boot3-starter-embedded-tests` fails: the Spring application context cannot be loaded because of a Micrometer version conflict. The Spring Boot 3 module forces `micrometer-core`/`micrometer-registry-prometheus` to `1.17.1` (from the shared global `version.micrometer` property), while Spring Boot 3.5.14's BOM manages `micrometer-commons`/`micrometer-observation` at `1.15.11`. Prometheus/core 1.17.1 calls `WarnThenDebugLogger.isEnabled()`, which does not exist in commons 1.15.11.

### Expected behavior
`SimpleApplicationTests` loads the application context and passes. Micrometer artifacts in the spring-boot-3 module should be consistent with the version managed by the Spring Boot 3 BOM.

### Actual behavior
The context fails to load with:
```
Caused by: org.springframework.context.ApplicationContextException: Unable to start web server
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
...
Caused by: java.lang.NoSuchMethodError: 'boolean io.micrometer.common.util.internal.logging.WarnThenDebugLogger.isEnabled()'
```
resulting in `IllegalStateException: Failed to load ApplicationContext`.

### How to Reproduce?
1. Check out `main` at commit `e9775d87cc` (`Bump version.micrometer from 1.16.6 to 1.17.1`) or later.
2. Run `mvn test -Dtest=SimpleApplicationTests` in `spring/spring-boot-3/it-tests/embedded-tests`.
3. The test fails with the stack trace above.

`mvn dependency:tree -Dincludes=io.micrometer` shows the skew: `micrometer-commons`/`observation`/`jakarta9` at `1.15.11` but `micrometer-core`/`registry-prometheus` at `1.17.1`.

### Environment
- Infinispan 16.3.0-SNAPSHOT (`main`)
- Spring Boot 3.5.14
- Introduced by commit e9775d87cc
