### PR TITLE
[#17991] SimpleApplicationTests fails in spring-boot-3 embedded IT — …

### LINKED ISSUE #17991: SimpleApplicationTests fails in spring-boot-3 embedded IT — Micrometer version mismatch
### Describe the bug
The `SimpleApplicationTests.contextLoads` test in `infinispan-spring-boot3-starter-embedded-tests` fails: the Spring application context cannot be loaded because of a Micrometer version conflict. The Spring Boot 3 module forces `micrometer-core`/`micrometer-registry-prometheus` to `1.17.1` (from the shared global `version.micrometer` property), while Spring Boot 3.5.14's BOM manages `micrometer-commons`/`micrometer-observation` at `1.15.11`. Prometheus/core 1.17.1 calls `WarnThenDebugLogger.isEnabled()`, which does not exist in commons 1.15.11.

### Expected behavior
`SimpleApplicationTests` loads the application context and passes. Micrometer artifacts in the spring-boot-3 module should be consistent with the version managed by the Spring Boot 3 BOM.

### Actual behavior
The context fails to load with:
```
Caused by: org.springframework.context.ApplicationContextException: Unable to start web server
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
...
Caused by: java.lang.NoSuchMethodError: 'boolean io.micrometer.common.util.internal.logging.WarnThenDebugLogger.isEnabled()'
```
resulting in `IllegalStateException: Failed to load ApplicationContext`.

### How to Reproduce?
1. Check out `main` at commit `e9775d87cc` (`Bump version.micrometer from 1.16.6 to 1.17.1`) or later.
2. Run `mvn test -Dtest=SimpleApplicationTests` in `spring/spring-boot-3/it-tests/embedded-tests`.
3. The test fails with the stack trace above.

`mvn dependency:tree -Dincludes=io.micrometer` shows the skew: `micrometer-commons`/`observation`/`jakarta9` at `1.15.11` but `micrometer-core`/`registry-prometheus` at `1.17.1`.

### Environment
- Infinispan 16.3.0-SNAPSHOT (`main`)
- Spring Boot 3.5.14
- Introduced by commit e9775d87cc

### PR DESCRIPTION
**Pull request by wburns**
…Micrometer version mismatch

Closes: #17991

Author Checklist (all must be checked):
- [ ] Commit message includes a reference to the corresponding [GitHub issue](https://github.com/infinispan/infinispan/issues) (e.g. commit message: "[#00000] Issue title...") and is formatted according to our [git message template](https://github.com/infinispan/infinispan/blob/main/.gitmessage).
- [ ] Commits have been squashed into self-contained units of work (e.g. 'WIP'- and 'Implements feedback'-style messages have been removed).
- [ ] The PR includes new/modified unit and integration tests that exercise the changes. Include additional manual testing instructions if necessary. If the PR does not include tests, clear justification **MUST** be provided.
- [ ] The PR includes new/modified documentation. If the PR does not require documentation changes, clear justification **MUST** be provided.
- [ ] Log messages of level `INFO` and above have been internationalized.
- [ ] If the PR affects performance, include before/after benchmarks.
- [ ] If the PR affects output (such as logs, CLI, Console), provide an example (text snippet/screenshot).
- [ ] If the PR requires a followup or is part of a larger body of work, ensure that relevant [GitHub issues](https://github.com/infinispan/infinispan/issues) have been created to track the additional work.

Reviewer Checklist (all must be checked):
- [ ] Code review
  - Are the changes reasonable?
  - Are there any use cases, integrations, inputs that haven't been considered in the implementation?
  - Is the code understandable? (KISS, comments)
  - Is there a better way to implement/write the functionality, code pieces?
  - Is formatting in line with the rest of the project? (checkstyle and spotless)
- [ ] Test review
  - Is the new test coverage rich enough to cover all the changes and considerations above?
  - Does the base functionality works as expected in the build project?
  - Does it behave as expected when given various inputs? (Valid and invalid, missing, partial)
  - Are there integrations to be considered? (Does the new functionality work well with the rest of the project, environment)
  -  Even if all above works as expected, are there weird behaviors to be improved on?
- [ ] Documentation review
  - Does the new/changed documentation cover the PR in sufficient matter?
  - For public API, are JavaDocs included for every new/changed class/method ?
  - For new features, does the documentation add/amend any usage examples ?
  - Grammar and syntax checks 
  - Does AsciiDoc generation report any WARN messages ?

### CODE REVIEW

**Comment by tristantarrant** [comment]
Merged, thanks
