### PR TITLE
ISPN-7426 Remove the no longer required hibernate-entitymanager depen…

### PR DESCRIPTION
**Pull request by Sanne**
…dency

 - https://issues.jboss.org/browse/ISPN-7426

### CODE REVIEW

**Comment by Sanne** [comment]
This should fix the build.

I'll follow up with separate PRs to merge some further improvements..

**Comment by galderz** [comment]
I've started the PR build manually.

**Comment by galderz** [comment]
Hey @Sanne, seems like there's a new failure that could be related to this change?

> EmbeddedAllTest.testAllEmbeddedJpaStore

**Comment by galderz** [comment]
```
org.infinispan.commons.CacheException: Unable to invoke method public void org.infinispan.persistence.manager.PersistenceManagerImpl.start() on object of type PersistenceManagerImpl
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetPublicMethods(Class.java:2902)
    at java.lang.Class.getMethods(Class.java:1615)
    at org.infinispan.commons.util.Util.getFactoryMethod(Util.java:220)
    at org.infinispan.commons.util.Util.getInstanceStrict(Util.java:259)
    at org.infinispan.commons.util.Util.getInstance(Util.java:238)
    at org.infinispan.persistence.factory.LocalClassLoaderCacheStoreFactory.createInstance(LocalClassLoaderCacheStoreFactory.java:25)
    at org.infinispan.persistence.factory.CacheStoreFactoryRegistry.createInstance(CacheStoreFactoryRegistry.java:39)
    at org.infinispan.persistence.manager.PersistenceManagerImpl.createLoadersAndWriters(PersistenceManagerImpl.java:592)
    at org.infinispan.persistence.manager.PersistenceManagerImpl.start(PersistenceManagerImpl.java:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.infinispan.commons.util.ReflectionUtil.invokeAccessibly(ReflectionUtil.java:168)
    at org.infinispan.factories.AbstractComponentRegistry$PrioritizedMethod.invoke(AbstractComponentRegistry.java:867)
    at org.infinispan.factories.AbstractComponentRegistry.invokeStartMethods(AbstractComponentRegistry.java:633)
    at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:622)
    at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:547)
    at org.infinispan.factories.ComponentRegistry.start(ComponentRegistry.java:231)
    at org.infinispan.cache.impl.CacheImpl.start(CacheImpl.java:803)
    at org.infinispan.cache.impl.AbstractDelegatingCache.start(AbstractDelegatingCache.java:411)
    at org.infinispan.manager.DefaultCacheManager.wireAndStartCache(DefaultCacheManager.java:638)
    at org.infinispan.manager.DefaultCacheManager.createCache(DefaultCacheManager.java:586)
    at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:450)
    at org.infinispan.manager.DefaultCacheManager.getCache(DefaultCacheManager.java:429)
```

**Comment by galderz** [comment]
I'm trying to replicate this failure locally

**Comment by galderz** [comment]
The root cause is:

```
java.lang.NoClassDefFoundError: org/hibernate/criterion/Projection
```

**Comment by galderz** [comment]
I'll open a jira for this other issue in a minute. @Sanne's fix unblocks build.

**Comment by galderz** [comment]
Issue for failing test is [ISPN-7453](https://issues.jboss.org/browse/ISPN-7453). Thx @Sanne

**Comment by wburns** [comment]
I have some fixes for the osgi stuff [1], but it still fails with [2]

[1] https://github.com/wburns/infinispan/commit/cd484a3cddbc13738cca68a21d11dee66edd84f2
[2] https://gist.github.com/wburns/1e054b10f045c33f755955ce3828e22a

**Comment by Sanne** [comment]
@galderz the bloody fix was trivial :) 673fd7a0f6cb6a88fddbc39cdc3bbbb5c7ce3d35

**Comment by galderz** [comment]
Thx @Sanne :)

**Comment by galderz** [comment]
> I have some fixes for the osgi stuff [1], but it still fails with [2]

Yeah, I was aware that there were still some failures, but went ahead with integrated this PR so that the build could at least finish.

**Comment by Sanne** [comment]
@slaskawi this was a problem caused by https://github.com/infinispan/infinispan/pull/4692#issuecomment-279360573

Will you follow up with a JIRA to fix the fact that Hibernate is an optional dependency of the JPA CacheStore?

**Comment by slaskawi** [comment]
@Sanne I created [ISPN-7463](https://issues.jboss.org/browse/ISPN-7463) however it's pretty low on my todo list. If you'd like to get it fast, I would kindly ask you to take ownership of this task.
